const db = window.imaposlaSupabase;
const state = {
  ready:false, session:null, user:null, profile:null, myCompany:null,
  jobs:[], companies:[], categories:[], cities:[], applications:[], adminProfiles:[], plans:[], orders:[], banners:[]
};

const menus = {
  candidate:[['Dashboard','/profil/dashboard'],['CV profil','/profil/cv'],['Prijave','/profil/prijave'],['Obavještenja','/profil/obavijesti'],['Podešavanja','/profil/podesavanja']],
  company:[['Dashboard','/firma/dashboard'],['Oglasi','/firma/oglasi'],['Novi oglas','/firma/novi-oglas'],['ATS','/firma/ats'],['Kandidati','/firma/kandidati'],['Pretplata','/firma/pretplata'],['Baneri','/firma/baneri'],['Podešavanja','/firma/podesavanja']],
  admin:[['Dashboard','/admin/dashboard'],['Uplate','/admin/uplate'],['Oglasi','/admin/oglasi'],['Korisnici','/admin/korisnici'],['Baneri','/admin/baneri'],['Statistike','/admin/statistike']]
};
const roleLabel = {candidate:'Kandidat',company:'Firma',admin:'Admin',guest:'Gost'};
const stageLabels = {applied:'Prijava',review:'Pregled',interview:'Razgovor',shortlist:'Uži izbor',offer:'Ponuda',rejected:'Odbijeno',hired:'Zaposlen'};
const stageOrder = ['applied','review','interview','shortlist','offer','hired','rejected'];
const jobStatus = {draft:'Nacrt',pending_review:'Čeka pregled',active:'Aktivan',paused:'Pauziran',rejected:'Odbijen',expired:'Istekao'};

function app(){return document.querySelector('#app')}
function h(v){return String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function slug(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'stavka'}
function path(){return(location.hash.replace('#','')||'/').split('?')[0]}
function initials(v){return String(v||'IP').split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase()}
function toast(msg){const el=document.querySelector('[data-toast]');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function go(to){location.hash=to}
function fmtDate(v){if(!v)return 'Bez roka';try{return new Date(v).toLocaleDateString('sr-ME')}catch{return v}}
function money(v){return v ? `${Number(v).toFixed(0)} EUR` : 'Po dogovoru'}
function role(){return state.profile?.role || 'guest'}
function roleHome(){return role()==='admin'?'/admin/dashboard':role()==='company'?'/firma/dashboard':role()==='candidate'?'/profil/dashboard':'/login'}
function badge(text,color='gray'){return `<span class="badge ${color}">${h(text)}</span>`}
function heading(title,text,action=''){return `<div class="section-head"><div><span class="eyebrow">imaposla.me</span><h1>${h(title)}</h1>${text?`<p class="sub">${h(text)}</p>`:''}</div>${action}</div>`}
function panel(title,text,action=''){return `<div class="card"><h3>${h(title)}</h3><p>${h(text)}</p>${action?`<div class="actions">${action}</div>`:''}</div>`}
function metric(label,value){return `<div class="metric"><strong>${h(value)}</strong><span>${h(label)}</span></div>`}
function empty(title,text,action=''){return `<div class="empty"><strong>${h(title)}</strong><p style="margin-top:8px">${h(text)}</p>${action?`<div class="actions">${action}</div>`:''}</div>`}
function statusBadge(status){const c=status==='active'||status==='hired'||status==='paid'?'green':status==='pending_review'||status==='pending'||status==='applied'?'orange':status==='paused'||status==='review'||status==='interview'||status==='shortlist'?'blue':status==='rejected'?'red':'gray';return badge(jobStatus[status]||stageLabels[status]||status,c)}
function safeCount(list){return Array.isArray(list)?list.length:0}
function requireAuth(target){if(!state.user){toast('Prvo se prijavi.');go('/login');return false}if(target&&role()!==target&&role()!=='admin'){toast('Ova sekcija nije dostupna tvom nalogu.');go(roleHome());return false}return true}

async function safeQuery(run,fallback=[]){try{const {data,error}=await run();if(error){console.warn(error.message);return fallback}return data||fallback}catch(err){console.warn(err);return fallback}}
async function init(){
  document.documentElement.dataset.theme=localStorage.getItem('imaposlaTheme')||'light';
  if(!db){state.ready=true;render();return}
  const {data}=await db.auth.getSession();state.session=data.session;state.user=data.session?.user||null;
  await loadData();state.ready=true;render();
  db.auth.onAuthStateChange(async(_e,session)=>{state.session=session;state.user=session?.user||null;await loadData();render()});
}
async function loadData(){
  await Promise.all([loadLookups(),loadPublicJobs(),loadPublicCompanies(),loadPlans()]);
  state.profile=null;state.myCompany=null;state.applications=[];state.adminProfiles=[];state.orders=[];state.banners=[];
  if(!state.user)return;
  state.profile=await safeQuery(()=>db.from('profiles').select('*').eq('id',state.user.id).maybeSingle(),null);
  if(state.profile?.role==='company'){
    state.myCompany=await safeQuery(()=>db.from('companies').select('*').eq('owner_id',state.user.id).maybeSingle(),null);
    if(state.myCompany){
      state.applications=await safeQuery(()=>db.from('job_applications').select('*,jobs(title,company_id),profiles(full_name,email,phone,city)').order('created_at',{ascending:false}));
      state.orders=await safeQuery(()=>db.from('orders').select('*,plans(name)').eq('company_id',state.myCompany.id).order('created_at',{ascending:false}));
      state.banners=await safeQuery(()=>db.from('banners').select('*').eq('company_id',state.myCompany.id).order('created_at',{ascending:false}));
    }
  }
  if(state.profile?.role==='candidate'){
    state.applications=await safeQuery(()=>db.from('job_applications').select('*,jobs(title,companies(name))').eq('candidate_id',state.user.id).order('created_at',{ascending:false}));
  }
  if(state.profile?.role==='admin'){
    const [profiles,apps,orders,banners]=await Promise.all([
      safeQuery(()=>db.from('profiles').select('*').order('created_at',{ascending:false})),
      safeQuery(()=>db.from('job_applications').select('*,jobs(title),profiles(full_name,email)').order('created_at',{ascending:false})),
      safeQuery(()=>db.from('orders').select('*,plans(name),companies(name)').order('created_at',{ascending:false})),
      safeQuery(()=>db.from('banners').select('*,companies(name)').order('created_at',{ascending:false}))
    ]);
    state.adminProfiles=profiles;state.applications=apps;state.orders=orders;state.banners=banners;
  }
}
async function loadLookups(){const [cats,cities]=await Promise.all([safeQuery(()=>db.from('categories').select('*').order('name')),safeQuery(()=>db.from('cities').select('*').order('name'))]);state.categories=cats;state.cities=cities}
async function loadPlans(){state.plans=await safeQuery(()=>db.from('plans').select('*').order('price_eur'))}
async function loadPublicJobs(){const data=await safeQuery(()=>db.from('jobs').select('id,title,slug,description,contract_type,salary_text,deadline,status,featured,company_id,companies(id,name,slug),categories(id,name),cities(id,name)').order('created_at',{ascending:false}));state.jobs=data.map(j=>({id:j.id,title:j.title,slug:j.slug,companyId:j.company_id,company:j.companies?.name||'Poslodavac',logo:initials(j.companies?.name),city:j.cities?.name||'Crna Gora',cityId:j.cities?.id,category:j.categories?.name||'Ostalo',categoryId:j.categories?.id,type:j.contract_type||'Po dogovoru',salary:j.salary_text||'Po dogovoru',deadline:j.deadline,status:j.status,featured:Boolean(j.featured),description:j.description||''}))}
async function loadPublicCompanies(){const data=await safeQuery(()=>db.from('companies').select('*').order('created_at',{ascending:false}));state.companies=data.map(c=>({id:c.id,name:c.name,slug:c.slug,logo:initials(c.name),city:c.city||'Crna Gora',industry:c.industry||'Poslodavac',approved:c.approved,about:c.description||'Profil poslodavca.'}))}

function searchPanel(){const params=new URLSearchParams(location.hash.split('?')[1]||'');const q=params.get('q')||'',city=params.get('city')||'',cat=params.get('category')||'';return `<form class="search-panel" data-search><input name="q" placeholder="Pozicija, firma ili vještina" value="${h(q)}"><select name="city"><option value="">Svi gradovi</option>${state.cities.map(c=>`<option ${city===c.name?'selected':''}>${h(c.name)}</option>`).join('')}</select><select name="category"><option value="">Sve kategorije</option>${state.categories.map(c=>`<option ${cat===c.name?'selected':''}>${h(c.name)}</option>`).join('')}</select><button>Traži</button></form>`}
function jobCard(job,admin=false){return `<article class="job-card ${job.featured?'featured':''}"><div class="logo">${h(job.logo)}</div><div><div class="tags">${job.featured?badge('Istaknuto','orange'):''}<span class="tag">${h(job.category)}</span><span class="tag">${h(job.type)}</span>${statusBadge(job.status)}</div><a class="job-title" href="#/oglasi/${slug(job.title)}-${job.id}">${h(job.title)}</a><div class="meta"><span>${h(job.company)}</span><span>${h(job.city)}</span><span>${h(job.salary)}</span><span>Rok ${h(fmtDate(job.deadline))}</span></div><p class="job-desc">${h(job.description)}</p></div><div class="job-actions">${admin?`<button class="btn lime sm" data-approve-job="${job.id}">Odobri</button><button class="btn ghost sm" data-feature-job="${job.id}">Istakni</button><button class="btn red sm" data-pause-job="${job.id}">Pauziraj</button>`:`<a class="btn ghost sm" href="#/oglasi/${slug(job.title)}-${job.id}">Detalji</a><button class="btn blue sm" data-apply="${job.id}">Prijavi se</button>`}</div></article>`}
function companyCard(c){return `<article class="company-card"><div class="logo">${h(c.logo)}</div><div><h3><a href="#/firme/${slug(c.name)}-${c.id}">${h(c.name)}</a></h3><p>${h(c.about)}</p><div class="meta"><span>${h(c.city)}</span><span>${h(c.industry)}</span>${c.approved?badge('Odobrena','green'):badge('Čeka odobrenje','orange')}</div></div></article>`}

function home(){app().innerHTML=`<section class="hero"><div class="panel"><span class="kicker">Poslovi u Crnoj Gori</span><h1>Nađi <span class="grad-text">posao</span> ili pravog kandidata bez lutanja.</h1><p class="lead">Javni oglasi, CV profili, prijave, ATS za firme i admin moderacija u jednom jasnom sistemu.</p><div class="hero-actions"><a class="btn blue" href="#/oglasi">Pretraži oglase</a><a class="btn ghost" href="#/za-firme">Rješenje za firme</a><a class="btn lime" href="${state.user?'#'+roleHome():'#/login'}">${state.user?'Moj dashboard':'Kreiraj nalog'}</a></div>${searchPanel()}</div><aside class="hero-side"><div class="metric-grid">${metric('aktivnih oglasa',state.jobs.filter(j=>j.status==='active').length)}${metric('poslodavaca',state.companies.length)}${metric('prijava',state.applications.length)}${metric('ulogovani kao',roleLabel[role()])}</div><div class="guide-card"><h3>Brz put do akcije</h3><p>Kandidat se prijavljuje na oglas. Firma objavljuje oglas i vodi selekciju. Admin odobrava firme, oglase, banere i uplate.</p></div></aside></section><section>${heading('Kako radi','Svaka uloga ima svoj dashboard i samo svoje dozvole.')}<div class="grid three">${panel('Kandidat','Popuni profil, dodaj kontakt, pošalji CV i prati status prijava.','<a class="btn blue sm" href="#/profil/dashboard">Kandidat</a>')}${panel('Firma','Kreiraj profil firme, objavi oglas, pregledaj prijave i pomjeraj kandidate kroz ATS.','<a class="btn lime sm" href="#/firma/dashboard">Firma</a>')}${panel('Admin','Odobri firme, oglase, banere i uplate iz jednog operativnog pregleda.','<a class="btn pink sm" href="#/admin/dashboard">Admin</a>')}</div></section><section>${heading('Izdvojeni oglasi','Najnoviji aktivni oglasi iz baze.')}<div class="job-list">${state.jobs.filter(j=>j.status==='active').slice(0,4).map(j=>jobCard(j)).join('')||empty('Još nema aktivnih oglasa','Prvi oglasi će se pojaviti čim ih firma pošalje i admin odobri.','<a class="btn blue" href="#/firma/novi-oglas">Objavi prvi oglas</a>')}</div></section>`}
function jobs(pref={}){const params=new URLSearchParams(location.hash.split('?')[1]||'');const q=(params.get('q')||'').toLowerCase();const city=pref.city||params.get('city')||'';const cat=pref.category||params.get('category')||'';const list=state.jobs.filter(j=>j.status==='active'&&(!q||`${j.title} ${j.company} ${j.category} ${j.description}`.toLowerCase().includes(q))&&(!city||j.city===city)&&(!cat||j.category===cat));app().innerHTML=`${heading('Oglasi za posao','Filtriraj oglase po poziciji, gradu i kategoriji.')}${searchPanel()}<div class="job-list">${list.map(j=>jobCard(j)).join('')||empty('Nema oglasa','Promijeni filtere ili se vrati kasnije.')}</div>`}
function jobDetail(raw){const id=Number((raw.match(/-(\d+)$/)||[])[1]);const job=state.jobs.find(j=>j.id===id);if(!job)return notFound();app().innerHTML=`<a class="btn ghost sm" href="#/oglasi">Nazad na oglase</a><section class="detail-layout" style="margin-top:16px"><div class="panel"><span class="eyebrow">${h(job.category)}</span><h1>${h(job.title)}</h1><p class="lead">${h(job.description)}</p><div class="tags">${badge(job.company,'blue')}${badge(job.city,'lime')}${badge(job.salary,'gray')}${badge(job.type,'gray')}${statusBadge(job.status)}</div></div><aside class="form-card sticky"><h2>Prijava</h2>${state.user?applicationForm(job):empty('Prijava zahtijeva nalog','Prijavi se kao kandidat i pošalji CV za manje od minut.','<a class="btn blue" href="#/login">Prijava</a>')}</aside></section>`}
function applicationForm(job){if(role()!=='candidate')return empty('Samo kandidat može aplicirati','Ako si firma ili admin, otvori oglas za pregled.');return `<label><span class="label">Poruka firmi</span><textarea class="textarea" id="coverLetter" maxlength="1200" placeholder="Kratko predstavljanje, iskustvo i dostupnost"></textarea></label><label class="file-input">Dodaj CV fajl<input id="cvFile" type="file" accept=".pdf,.doc,.docx"></label><button class="btn blue" data-submit-application="${job.id}">Pošalji prijavu</button><p class="notice">Firma vidi tvoje kontakt podatke iz profila i CV koji pošalješ uz prijavu.</p>`}
function citiesPage(){app().innerHTML=`${heading('Gradovi','Brz pregled poslova po lokaciji.')}<div class="grid three">${state.cities.map(c=>`<a class="card link-card" href="#/gradovi/${encodeURIComponent(c.name)}"><h3>${h(c.name)}</h3><p>Pogledaj aktivne oglase u ovom gradu.</p></a>`).join('')||empty('Nema gradova','Dodaj gradove u Supabase tabelu cities.')}</div>`}
function categoriesPage(){app().innerHTML=`${heading('Kategorije','Oglasi grupisani po oblasti rada.')}<div class="grid three">${state.categories.map(c=>`<a class="card link-card" href="#/kategorije/${encodeURIComponent(c.name)}"><h3>${h(c.name)}</h3><p>Pogledaj poslove iz ove kategorije.</p></a>`).join('')||empty('Nema kategorija','Dodaj kategorije u Supabase tabelu categories.')}</div>`}
function companies(){app().innerHTML=`${heading('Firme','Javni profili odobrenih poslodavaca.')}<div class="grid two">${state.companies.map(companyCard).join('')||empty('Nema firmi','Firme se prikazuju nakon admin odobrenja.')}</div>`}
function companyDetail(raw){const id=Number((raw.match(/-(\d+)$/)||[])[1]);const c=state.companies.find(x=>x.id===id);if(!c)return notFound();const list=state.jobs.filter(j=>j.companyId===c.id&&j.status==='active');app().innerHTML=`<a class="btn ghost sm" href="#/firme">Nazad na firme</a><div class="panel" style="margin-top:16px"><span class="eyebrow">Profil firme</span><h1>${h(c.name)}</h1><p class="lead">${h(c.about)}</p><div class="tags">${badge(c.city,'lime')}${badge(c.industry,'gray')}</div></div>${heading('Aktivni oglasi','Svi javni oglasi ovog poslodavca.')}<div class="job-list">${list.map(j=>jobCard(j)).join('')||empty('Nema aktivnih oglasa','Ova firma trenutno nema javno aktivnih oglasa.')}</div>`}
function forCompanies(){app().innerHTML=`<section class="panel"><span class="eyebrow">Za poslodavce</span><h1>Objavite oglas, pratite prijave i vodite selekciju.</h1><p class="lead">Firma dobija dashboard, oglase, ATS, bazu prijava, pretplatu i banere. Admin odobrava javne korake da platforma ostane uredna.</p><div class="hero-actions"><a class="btn blue" href="#/login">Registruj firmu</a><a class="btn ghost" href="#/firma/dashboard">Dashboard firme</a></div></section>${heading('Flow za firmu','Kratko, pregledno i bez nepotrebnih koraka.')}<div class="grid three">${panel('1. Profil firme','Upiši naziv, grad, industriju i opis. Admin odobrava javni prikaz.')}${panel('2. Oglas','Unesi poziciju, grad, kategoriju, platu i opis. Oglas ide na pregled.')}${panel('3. ATS','Prijave stižu u kanban, kandidat se pomjera kroz faze i sve ostaje zabilježeno.')}</div>`}

function shell(roleName,page){if(!requireAuth(roleName))return;app().innerHTML=`<div class="shell"><aside class="sidebar"><div class="side-head"><div class="side-avatar">${initials(state.profile?.full_name||state.profile?.email)}</div><b>${roleLabel[roleName]}</b><small>${h(state.profile?.email||state.user?.email||'')}</small></div><button data-signout>Odjava</button>${menus[roleName].map(([label,url])=>`<a class="${path()===url?'active':''}" href="#${url}">${label}</a>`).join('')}</aside><section>${rolePage(roleName,page)}</section></div>`}
function rolePage(roleName,page){return roleName==='candidate'?candidate(page):roleName==='company'?company(page):admin(page)}
function candidate(page){if(page==='cv'||page==='settings')return heading(page==='cv'?'CV profil':'Podešavanja','Podaci koje vidi firma kada pošalješ prijavu.')+profileForm();if(page==='applications')return heading('Moje prijave','Statusi svih prijava koje si poslao.')+applicationsTable(state.applications,'candidate');if(page==='notifications')return heading('Obavještenja','Promjene statusa prijava i važne poruke.')+notifications();return heading('Kandidat dashboard','Brz pregled profila, prijava i preporučenih oglasa.')+`<div class="dash-grid">${metric('Aktivne prijave',state.applications.length)}${metric('Dostupni oglasi',state.jobs.filter(j=>j.status==='active').length)}${metric('Profil',state.profile?.full_name?'Popunjen':'Dopuniti')}${metric('Uloga','Kandidat')}</div><div class="job-list">${state.jobs.filter(j=>j.status==='active').slice(0,3).map(j=>jobCard(j)).join('')||empty('Nema oglasa','Trenutno nema aktivnih oglasa.')}</div>`}
function company(page){if(!state.myCompany&&page!=='settings')return heading('Profil firme','Prvo kreiraj profil firme. Poslije odobrenja možeš javno nastupati kao poslodavac.')+companyForm();if(page==='jobs')return heading('Moji oglasi','Pregled statusa i prijava po oglasu.','<a class="btn blue" href="#/firma/novi-oglas">Novi oglas</a>')+`<div class="job-list">${state.jobs.filter(j=>j.companyId===state.myCompany?.id).map(j=>jobCard(j)).join('')||empty('Nema oglasa','Objavi prvi oglas i pošalji ga na odobrenje.','<a class="btn blue" href="#/firma/novi-oglas">Novi oglas</a>')}</div>`;if(page==='new-job')return heading('Novi oglas','Oglas se šalje adminu na pregled prije javnog prikaza.')+jobForm();if(page==='ats')return heading('ATS prijave','Pomjeraj kandidate kroz faze selekcije.')+atsBoard();if(page==='candidates')return heading('Kandidati','Baza kandidata nastaje iz prijava na tvoje oglase.')+applicationsTable(state.applications,'company');if(page==='billing')return billingPage();if(page==='banners')return bannersPage();if(page==='settings')return heading('Podešavanja firme','Logo, opis, kontakt i status odobrenja.')+companyForm();return heading('Firma dashboard','Brze akcije, oglasi i prijave koje traže pažnju.')+`<div class="dash-grid">${metric('Oglasi',state.jobs.filter(j=>j.companyId===state.myCompany?.id).length)}${metric('Prijave',state.applications.length)}${metric('Status firme',state.myCompany?.approved?'Odobrena':'Čeka')}${metric('Uplate',state.orders.length)}</div><div class="grid two">${panel('Sljedeći korak','Objavi oglas ili otvori ATS da pregledaš prijave.','<a class="btn blue sm" href="#/firma/novi-oglas">Novi oglas</a><a class="btn ghost sm" href="#/firma/ats">ATS</a>')}${panel('Javni status',state.myCompany?.approved?'Firma je odobrena i može imati javne oglase.':'Firma čeka admin odobrenje prije javnog prikaza.')}</div>`}
function admin(page){if(page==='payments')return heading('Uplate i kodovi','Potvrdi uplate i generiši aktivacione kodove.')+ordersTable(true);if(page==='jobs')return heading('Moderacija oglasa','Odobravanje, isticanje i pauziranje oglasa.')+`<div class="job-list">${state.jobs.map(j=>jobCard(j,true)).join('')||empty('Nema oglasa','Još nema oglasa za moderaciju.')}</div>`;if(page==='users')return heading('Korisnici','Kandidati, firme i status verifikacije.')+usersTable()+heading('Firme za odobrenje','Odobri firmu da bi njen profil mogao biti javan.')+`<div class="grid two">${state.companies.map(adminCompanyCard).join('')||empty('Nema firmi','Firme se pojavljuju nakon registracije.')}</div>`;if(page==='banners')return heading('Baneri','Pregled i odobravanje promo pozicija.')+bannersTable(true);if(page==='stats')return heading('Statistike','Operativni puls platforme.')+`<div class="dash-grid">${metric('Korisnici',state.adminProfiles.length)}${metric('Oglasi',state.jobs.length)}${metric('Prijave',state.applications.length)}${metric('Firme',state.companies.length)}</div><div class="grid three">${panel('Aktivni oglasi',String(state.jobs.filter(j=>j.status==='active').length))}${panel('Čekaju pregled',String(state.jobs.filter(j=>j.status==='pending_review').length))}${panel('Uplate',String(state.orders.length))}</div>`;return heading('Admin dashboard','Operativni pregled zadataka.')+`<div class="dash-grid">${metric('Firme za pregled',state.companies.filter(c=>!c.approved).length)}${metric('Oglasi za pregled',state.jobs.filter(j=>j.status!=='active').length)}${metric('Korisnici',state.adminProfiles.length)}${metric('Prijave',state.applications.length)}</div><div class="grid two">${panel('Prioritet','Odobri firme i oglase koji čekaju pregled.','<a class="btn blue sm" href="#/admin/korisnici">Firme</a><a class="btn lime sm" href="#/admin/oglasi">Oglasi</a>')}${panel('Kontrola','Admin upravlja javnim statusima, uplatama i banerima.')}</div>`}

function profileForm(){return `<form class="form-card" data-profile-form><div class="form-grid"><label><span class="label">Ime i prezime</span><input class="field" name="full_name" required value="${h(state.profile?.full_name||'')}"></label><label><span class="label">Telefon</span><input class="field" name="phone" value="${h(state.profile?.phone||'')}"></label></div><label><span class="label">Grad</span><input class="field" name="city" value="${h(state.profile?.city||'')}"></label><button class="btn blue">Sačuvaj profil</button><p class="notice">Kontakt podaci se koriste za prijave koje sam pošalješ firmama.</p></form>`}
function companyForm(){const c=state.myCompany;return `<form class="form-card" data-company-form><label><span class="label">Naziv firme</span><input class="field" name="name" required value="${h(c?.name||'')}"></label><div class="form-grid"><label><span class="label">Grad</span><input class="field" name="city" value="${h(c?.city||'')}"></label><label><span class="label">Industrija</span><input class="field" name="industry" value="${h(c?.industry||'')}"></label></div><label><span class="label">Opis firme</span><textarea class="textarea" name="description" required>${h(c?.description||'')}</textarea></label><button class="btn blue">Sačuvaj firmu</button><p class="notice">Status: ${c?.approved?'odobrena firma':'čeka admin odobrenje'}.</p></form>`}
function jobForm(){return `<form class="form-card" data-job-form><label><span class="label">Naziv pozicije</span><input class="field" name="title" required placeholder="npr. Konobar/konobarica"></label><div class="form-grid"><label><span class="label">Grad</span><select class="select" name="city_id" required>${state.cities.map(c=>`<option value="${c.id}">${h(c.name)}</option>`).join('')}</select></label><label><span class="label">Kategorija</span><select class="select" name="category_id" required>${state.categories.map(c=>`<option value="${c.id}">${h(c.name)}</option>`).join('')}</select></label></div><div class="form-grid"><label><span class="label">Tip ugovora</span><input class="field" name="contract_type" placeholder="Stalni rad, sezonski..."></label><label><span class="label">Plata</span><input class="field" name="salary_text" placeholder="Po dogovoru"></label></div><label><span class="label">Rok prijave</span><input class="field" type="date" name="deadline"></label><label><span class="label">Opis oglasa</span><textarea class="textarea" name="description" required placeholder="Opis posla, uslovi, šta nudite..."></textarea></label><button class="btn blue">Pošalji na odobrenje</button></form>`}
function loginPage(){app().innerHTML=`<section class="grid two"><form class="form-card" data-auth-form="signin"><span class="eyebrow">Prijava</span><h1>Uđi na nalog</h1><label><span class="label">Email</span><input class="field" name="email" type="email" autocomplete="email" required></label><label><span class="label">Lozinka</span><input class="field" name="password" type="password" autocomplete="current-password" required></label><button class="btn blue">Prijavi se</button></form><form class="form-card" data-auth-form="signup"><span class="eyebrow">Registracija</span><h1>Novi nalog</h1><label><span class="label">Tip naloga</span><select class="select" name="role"><option value="candidate">Kandidat</option><option value="company">Firma</option></select></label><label><span class="label">Email</span><input class="field" name="email" type="email" autocomplete="email" required></label><label><span class="label">Lozinka</span><input class="field" name="password" type="password" autocomplete="new-password" minlength="8" required></label><button class="btn lime">Kreiraj nalog</button><p class="notice">Admin nalog se ne kreira javno. Admin ulogu dodjeljuje vlasnik sistema kroz Supabase.</p></form></section>`}
function applicationsTable(rows,mode){return `<div class="table-card">${rows.map(a=>`<div class="table-row"><div><strong>${h(a.jobs?.title||a.job_title||'Prijava')}</strong><small>${h(a.reference_code||'')}</small></div><div>${h(a.profiles?.full_name||a.profiles?.email||a.candidate_id||a.jobs?.companies?.name||'')}</div><div>${statusBadge(a.stage)}</div><div>${mode!=='candidate'?stageActions(a):h(fmtDate(a.created_at))}</div></div>`).join('')||empty('Nema prijava','Prijave će se prikazati ovdje čim kandidat aplicira.')}</div>`}
function stageActions(a){const idx=stageOrder.indexOf(a.stage);return `<div class="actions" style="margin:0"><button class="btn ghost xs" data-stage-prev="${a.id}" ${idx<=0?'disabled':''}>Nazad</button><button class="btn blue xs" data-stage-next="${a.id}" ${idx<0||idx>=stageOrder.length-2?'disabled':''}>Dalje</button></div>`}
function atsBoard(){const cols=stageOrder.map(stage=>{const rows=state.applications.filter(a=>a.stage===stage);return `<div class="kanban-column"><div class="kanban-head"><h4>${stageLabels[stage]}</h4><span class="badge gray">${rows.length}</span></div>${rows.map(a=>`<div class="candidate-card"><strong>${h(a.profiles?.full_name||a.profiles?.email||'Kandidat')}</strong><p>${h(a.jobs?.title||'Prijava')} · ${h(a.profiles?.city||'')}</p>${statusBadge(a.stage)}<div class="candidate-actions">${stageActions(a)}</div></div>`).join('')||'<p class="sub" style="text-align:center;padding:18px">—</p>'}</div>`}).join('');return `<div class="kanban-wrap"><div class="kanban">${cols}</div></div>`}
function notifications(){return state.applications.length?`<div class="grid two">${state.applications.map(a=>panel(a.jobs?.title||'Prijava',`Status prijave: ${stageLabels[a.stage]||a.stage}`)).join('')}</div>`:empty('Nema obavještenja','Kada se status prijave promijeni, ovdje ćeš ga vidjeti.')}
function adminCompanyCard(c){return `<article class="card"><h3>${h(c.name)}</h3><p>${h(c.city)} · ${h(c.industry)}</p><div class="actions">${c.approved?badge('Odobrena','green'):`<button class="btn blue sm" data-approve-company="${c.id}">Odobri firmu</button>`}</div></article>`}
function usersTable(){return `<div class="table-card">${state.adminProfiles.map(p=>`<div class="table-row"><div><strong>${h(p.full_name||p.email)}</strong><small>${h(p.email)}</small></div><div>${badge(roleLabel[p.role]||p.role,'gray')}</div><div>${h(p.city||'')}</div><div>${h(fmtDate(p.created_at))}</div></div>`).join('')||empty('Nema korisnika','Korisnici se pojavljuju nakon registracije.')}</div>`}
function billingPage(){const plans=state.plans.length?state.plans:[{id:0,name:'Starter',price_eur:25,features:['3 aktivna oglasa','10 kredita','Osnovna podrška']},{id:0,name:'Growth',price_eur:80,features:['10 aktivnih oglasa','50 kredita','ATS']},{id:0,name:'Pro',price_eur:200,features:['Neograničeni oglasi','Baneri','Napredna statistika']}];return heading('Pretplata','Izaberi plan i pošalji zahtjev za uplatu.')+`<div class="grid three">${plans.map(p=>`<div class="plan-card"><h2>${h(p.name)}</h2><div class="plan-price">${money(p.price_eur)}</div><ul class="plan-features">${(p.features||[]).map(f=>`<li>${h(f)}</li>`).join('')}</ul><div class="actions"><button class="btn blue sm" data-order-plan="${p.id}" data-plan-name="${h(p.name)}" data-plan-price="${p.price_eur}">Naruči</button></div></div>`).join('')}</div>${heading('Moje narudžbe','Status uplata i aktivacioni kodovi.')}${ordersTable(false)}`}
function ordersTable(adminMode){return `<div class="table-card">${state.orders.map(o=>`<div class="table-row"><div><strong>${h(o.payment_reference||('IP-'+o.id))}</strong><small>${h(o.companies?.name||state.myCompany?.name||'Firma')}</small></div><div>${h(o.plans?.name||o.plan_name||'Plan')}<small>${money(o.amount_eur)}</small></div><div>${statusBadge(o.status)}</div><div>${adminMode&&o.status==='pending'?`<button class="btn blue xs" data-confirm-order="${o.id}">Potvrdi</button>`:h(o.activation_code||fmtDate(o.created_at))}</div></div>`).join('')||empty('Nema uplata','Narudžbe planova će se prikazati ovdje.')}</div>`}
function bannersPage(){return heading('Baneri','Pošalji zahtjev za promo poziciju. Admin odobrava javni prikaz.')+`<form class="form-card" data-banner-form><label><span class="label">Naslov banera</span><input class="field" name="title" required></label><label><span class="label">Link</span><input class="field" name="target_url" placeholder="https://..."></label><label><span class="label">Pozicija</span><select class="select" name="placement"><option value="home">Početna</option><option value="jobs">Oglasi</option></select></label><button class="btn blue">Pošalji baner</button></form>${heading('Moji baneri','Status promo zahtjeva.')}${bannersTable(false)}`}
function bannersTable(adminMode){return `<div class="table-card">${state.banners.map(b=>`<div class="table-row"><div><strong>${h(b.title)}</strong><small>${h(b.target_url||'Bez linka')}</small></div><div>${h(b.placement)}</div><div>${b.approved?badge('Odobren','green'):badge('Čeka','orange')}</div><div>${adminMode&&!b.approved?`<button class="btn blue xs" data-approve-banner="${b.id}">Odobri</button>`:h(fmtDate(b.created_at))}</div></div>`).join('')||empty('Nema banera','Baneri će se pojaviti nakon slanja zahtjeva.')}</div>`}
function staticPage(title,text){app().innerHTML=`<section class="panel"><h1>${h(title)}</h1><p class="lead">${h(text)}</p></section>`}
function sitemap(){staticPage('Sitemap','Javne stranice: početna, oglasi, gradovi, kategorije, firme i login. Svaka uloga ima svoj dashboard.')}
function notFound(){staticPage('Stranica nije pronađena','Provjeri adresu ili se vrati na početnu.')}
function setupMissing(){app().innerHTML=`<section class="panel"><span class="eyebrow">Podešavanje</span><h1>Sajt je spreman, baza nije povezana.</h1><p class="lead">Provjeri Supabase URL i publishable key u fajlu supabase.js. Korisnicima se ne prikazuje kod, samo uredna poruka dok se veza ne uključi.</p></section>`}

const routes={'/':home,'/oglasi':jobs,'/gradovi':citiesPage,'/kategorije':categoriesPage,'/firme':companies,'/za-firme':forCompanies,'/login':loginPage,'/profil/dashboard':()=>shell('candidate','dashboard'),'/profil/cv':()=>shell('candidate','cv'),'/profil/prijave':()=>shell('candidate','applications'),'/profil/obavijesti':()=>shell('candidate','notifications'),'/profil/podesavanja':()=>shell('candidate','settings'),'/firma/dashboard':()=>shell('company','dashboard'),'/firma/oglasi':()=>shell('company','jobs'),'/firma/novi-oglas':()=>shell('company','new-job'),'/firma/ats':()=>shell('company','ats'),'/firma/kandidati':()=>shell('company','candidates'),'/firma/pretplata':()=>shell('company','billing'),'/firma/baneri':()=>shell('company','banners'),'/firma/podesavanja':()=>shell('company','settings'),'/admin/dashboard':()=>shell('admin','dashboard'),'/admin/uplate':()=>shell('admin','payments'),'/admin/oglasi':()=>shell('admin','jobs'),'/admin/korisnici':()=>shell('admin','users'),'/admin/baneri':()=>shell('admin','banners'),'/admin/statistike':()=>shell('admin','stats'),'/politika-privatnosti':()=>staticPage('Politika privatnosti','Čuvamo podatke naloga, prijava i CV fajlova samo za svrhu zapošljavanja i komunikacije između kandidata i poslodavaca.'),'/uslovi-koristenja':()=>staticPage('Uslovi korišćenja','Korisnici su odgovorni za tačnost podataka, a oglasi i firme prolaze admin pregled prije javnog prikaza.'),'/sitemap':sitemap};
function render(){document.querySelector('[data-role-pill]').textContent=roleLabel[role()];if(!state.ready){app().innerHTML='<section class="panel"><h1>Učitavanje</h1><p class="lead">Spremamo podatke.</p></section>';return}if(!db)return setupMissing();const p=path();const job=p.match(/^\/oglasi\/(.+)/),company=p.match(/^\/firme\/(.+)/),city=p.match(/^\/gradovi\/(.+)/),cat=p.match(/^\/kategorije\/(.+)/);if(job)return jobDetail(job[1]);if(company)return companyDetail(company[1]);if(city)return jobs({city:decodeURIComponent(city[1])});if(cat)return jobs({category:decodeURIComponent(cat[1])});(routes[p]||notFound)();document.querySelectorAll('.desktop-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+p));app().focus({preventScroll:true})}

document.addEventListener('submit',async e=>{
  if(e.target.matches('[data-search]')){e.preventDefault();const d=new FormData(e.target),params=new URLSearchParams();['q','city','category'].forEach(k=>{if(d.get(k))params.set(k,d.get(k))});location.hash='/oglasi'+(params.toString()?`?${params}`:'');return}
  const auth=e.target.closest('[data-auth-form]');if(auth){e.preventDefault();const d=new FormData(auth),email=String(d.get('email')||''),password=String(d.get('password')||''),requestedRole=String(d.get('role')||'candidate');try{if(auth.dataset.authForm==='signup'){const {error}=await db.auth.signUp({email,password,options:{data:{role:requestedRole}}});if(error)throw error;toast('Nalog je kreiran. Prijavi se ili potvrdi email ako je potvrda uključena.')}else{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;toast('Prijava uspješna.');go(roleHome())}}catch(err){toast(err.message||'Prijava nije uspjela.')}return}
  const profile=e.target.closest('[data-profile-form]');if(profile){e.preventDefault();const data=Object.fromEntries(new FormData(profile));const {error}=await db.from('profiles').update(data).eq('id',state.user.id);if(error)return toast(error.message);await loadData();toast('Profil je sačuvan.');render();return}
  const company=e.target.closest('[data-company-form]');if(company){e.preventDefault();const data=Object.fromEntries(new FormData(company));data.owner_id=state.user.id;data.slug=slug(data.name);const query=state.myCompany?db.from('companies').update(data).eq('id',state.myCompany.id):db.from('companies').insert(data);const {error}=await query;if(error)return toast(error.message);await loadData();toast('Firma je sačuvana.');render();return}
  const job=e.target.closest('[data-job-form]');if(job){e.preventDefault();if(!state.myCompany)return toast('Prvo kreiraj firmu.');const data=Object.fromEntries(new FormData(job));data.company_id=state.myCompany.id;data.slug=slug(data.title)+'-'+Date.now();data.status='pending_review';const {error}=await db.from('jobs').insert(data);if(error)return toast(error.message);await loadData();toast('Oglas je poslat na odobrenje.');go('/firma/oglasi');return}
  const banner=e.target.closest('[data-banner-form]');if(banner){e.preventDefault();if(!state.myCompany)return toast('Prvo kreiraj firmu.');const data=Object.fromEntries(new FormData(banner));data.company_id=state.myCompany.id;data.approved=false;const {error}=await db.from('banners').insert(data);if(error)return toast(error.message);await loadData();toast('Baner je poslat na odobrenje.');render();return}
});

document.addEventListener('click',async e=>{const t=e.target.closest('button,a');if(!t)return;
  if(t.matches('[data-action="toggle-menu"]'))document.querySelector('[data-mobile-menu]').classList.toggle('open');
  if(t.matches('[data-action="toggle-theme"]')){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('imaposlaTheme',next)}
  if(t.matches('[data-action="open-login"]'))go('/login');
  if(t.matches('[data-signout]')){await db.auth.signOut();toast('Odjavljen si.');go('/')}
  if(t.matches('[data-apply]')){const id=Number(t.dataset.apply);if(!state.user)return go('/login');go(`/oglasi/${slug(state.jobs.find(j=>j.id===id)?.title||'oglas')}-${id}`)}
  if(t.matches('[data-submit-application]')){if(!requireAuth('candidate'))return;const jobId=Number(t.dataset.submitApplication);let cvPath=null;const file=document.querySelector('#cvFile')?.files?.[0];if(file){const filePath=`${state.user.id}/${Date.now()}-${file.name}`;const upload=await db.storage.from('candidate-cv').upload(filePath,file,{upsert:false});if(upload.error)return toast(upload.error.message);cvPath=filePath}const row={job_id:jobId,candidate_id:state.user.id,cover_letter:document.querySelector('#coverLetter')?.value||'',cv_path:cvPath,reference_code:'IP-'+Date.now()};const {error}=await db.from('job_applications').insert(row);if(error)return toast(error.message);await loadData();toast('Prijava je poslata.');go('/profil/prijave')}
  if(t.matches('[data-approve-job]'))await updateJob(Number(t.dataset.approveJob),{status:'active'},'Oglas je odobren.');
  if(t.matches('[data-pause-job]'))await updateJob(Number(t.dataset.pauseJob),{status:'paused'},'Oglas je pauziran.');
  if(t.matches('[data-feature-job]'))await updateJob(Number(t.dataset.featureJob),{featured:true},'Oglas je istaknut.');
  if(t.matches('[data-approve-company]')){const {error}=await db.from('companies').update({approved:true}).eq('id',Number(t.dataset.approveCompany));if(error)return toast(error.message);await loadData();toast('Firma je odobrena.');render()}
  if(t.matches('[data-stage-next]'))await moveStage(Number(t.dataset.stageNext),1);
  if(t.matches('[data-stage-prev]'))await moveStage(Number(t.dataset.stagePrev),-1);
  if(t.matches('[data-order-plan]'))await orderPlan(t);
  if(t.matches('[data-confirm-order]'))await confirmOrder(Number(t.dataset.confirmOrder));
  if(t.matches('[data-approve-banner]')){const {error}=await db.from('banners').update({approved:true}).eq('id',Number(t.dataset.approveBanner));if(error)return toast(error.message);await loadData();toast('Baner je odobren.');render()}
});
async function updateJob(id,patch,msg){const {error}=await db.from('jobs').update(patch).eq('id',id);if(error)return toast(error.message);await loadData();toast(msg);render()}
async function moveStage(id,dir){const appRow=state.applications.find(a=>a.id===id);if(!appRow)return;const idx=stageOrder.indexOf(appRow.stage);const next=stageOrder[Math.max(0,Math.min(stageOrder.length-1,idx+dir))];const {error}=await db.from('job_applications').update({stage:next}).eq('id',id);if(error)return toast(error.message);await loadData();toast(`Status: ${stageLabels[next]}`);render()}
async function orderPlan(btn){if(!state.myCompany)return toast('Prvo kreiraj firmu.');const planId=Number(btn.dataset.orderPlan)||null;const amount=Number(btn.dataset.planPrice)||0;const row={company_id:state.myCompany.id,plan_id:planId,status:'pending',amount_eur:amount,payment_reference:'IP-'+Date.now()};const {error}=await db.from('orders').insert(row);if(error)return toast(error.message);await loadData();toast('Narudžba je kreirana. Admin potvrđuje uplatu.');render()}
async function confirmOrder(id){const code='IP-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,6).toUpperCase();const {error}=await db.from('orders').update({status:'paid',activation_code:code,confirmed_by:state.user.id,confirmed_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);await loadData();toast('Uplata potvrđena. Kod je generisan.');render()}

window.addEventListener('hashchange',render);
app().innerHTML='<section class="panel"><h1>Učitavanje</h1><p class="lead">Spremamo imaposla.me.</p></section>';
init();
