const db = window.imaposlaSupabase;
const state = {
  mode: 'demo',
  role: localStorage.getItem('imaposlaRole') || 'guest',
  jobs: [
    { id: 1, title: 'Konobar/konobarica', company: 'Hotel Sunce', logo: 'HS', city: 'Budva', category: 'Ugostiteljstvo', type: 'Sezonski', salary: '900-1200 EUR', deadline: '15.06.2026', featured: true, description: 'Rad u restoranu hotela, smjenski raspored, obezbijedjen obrok i mentorstvo.' },
    { id: 2, title: 'Prodavac u maloprodaji', company: 'Market Plus', logo: 'MP', city: 'Podgorica', category: 'Prodaja', type: 'Stalni rad', salary: '750-950 EUR', deadline: '01.06.2026', featured: false, description: 'Rad sa kupcima, punjenje polica, kasa i urednost prodajnog prostora.' },
    { id: 3, title: 'Recepcionar', company: 'Adria Suites', logo: 'AS', city: 'Kotor', category: 'Turizam', type: 'Stalni rad', salary: '850-1100 EUR', deadline: '20.06.2026', featured: true, description: 'Komunikacija sa gostima, rezervacije, check-in i osnovna administracija.' },
    { id: 4, title: 'Junior knjigovodja', company: 'FinOffice', logo: 'FO', city: 'Niksic', category: 'Administracija', type: 'Stalni rad', salary: '800-1000 EUR', deadline: '10.06.2026', featured: false, description: 'Unos dokumentacije, priprema izvjestaja i podrska glavnom racunovodji.' }
  ],
  companies: [
    { id: 1, name: 'Hotel Sunce', logo: 'HS', city: 'Budva', industry: 'Ugostiteljstvo', jobs: 3, about: 'Sezonski i stalni poslovi u hotelijerstvu.' },
    { id: 2, name: 'Market Plus', logo: 'MP', city: 'Podgorica', industry: 'Trgovina', jobs: 5, about: 'Lanac maloprodajnih objekata sa stabilnim timovima.' },
    { id: 3, name: 'Adria Suites', logo: 'AS', city: 'Kotor', industry: 'Turizam', jobs: 2, about: 'Butik smjestaj i premium usluga za goste.' }
  ],
  applications: [
    { id: 1, candidate: 'Milica Radovic', title: 'Konobarica', city: 'Bar', stage: 'Prijava', labels: ['Iskustvo'], note: 'Ima 3 sezone iskustva.' },
    { id: 2, candidate: 'Ivan Vukcevic', title: 'Student', city: 'Budva', stage: 'Razgovor', labels: ['Sezona'], note: 'Dostupan od juna.' },
    { id: 3, candidate: 'Sara Popovic', title: 'Prodaja', city: 'Podgorica', stage: 'Uzi izbor', labels: ['Preporuka'], note: 'Radila na kasi.' },
    { id: 4, candidate: 'Marko Jovanovic', title: 'Recepcija', city: 'Kotor', stage: 'Ponuda', labels: ['Engleski'], note: 'Odlican engleski.' }
  ],
  orders: [
    { id: 'IP-2026-1001', company: 'Hotel Sunce', plan: 'Growth', status: 'Ceka uplatu' },
    { id: 'IP-2026-1002', company: 'Market Plus', plan: 'Starter', status: 'Potvrdjeno' }
  ]
};

const roleTitle = { candidate: 'Kandidat', company: 'Firma', admin: 'Admin' };
const menus = {
  candidate: [['Dashboard','/profil/dashboard'],['CV profil','/profil/cv'],['Prijave','/profil/prijave'],['Obavjestenja','/profil/obavijesti'],['Podesavanja','/profil/podesavanja']],
  company: [['Dashboard','/firma/dashboard'],['Oglasi','/firma/oglasi'],['Novi oglas','/firma/novi-oglas'],['ATS','/firma/ats'],['Kandidati','/firma/kandidati'],['Pretplata','/firma/pretplata'],['Baneri','/firma/baneri'],['Podesavanja','/firma/podesavanja']],
  admin: [['Dashboard','/admin/dashboard'],['Uplate','/admin/uplate'],['Oglasi','/admin/oglasi'],['Korisnici','/admin/korisnici'],['Baneri','/admin/baneri'],['Statistike','/admin/statistike']]
};

function app(){ return document.querySelector('#app'); }
function h(value){ return String(value ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); }
function slug(value){ return String(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''); }
function path(){ return (location.hash.replace('#','') || '/').split('?')[0]; }
function initials(value){ return String(value || 'IP').split(/\s+/).filter(Boolean).slice(0,2).map(p => p[0]).join('').toUpperCase(); }
function cities(){ return [...new Set(state.jobs.map(j => j.city))]; }
function categories(){ return [...new Set(state.jobs.map(j => j.category))]; }
function toast(message){ const el=document.querySelector('[data-toast]'); el.textContent=message; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.classList.remove('show'),2500); }
function go(to){ location.hash = to; }
function panel(title, text){ return `<div class="card"><h3>${title}</h3><p>${text}</p></div>`; }
function metric(label, value){ return `<div class="metric"><strong>${value}</strong><span>${label}</span></div>`; }
function heading(title, text){ return `<div class="section-head"><div><h1>${title}</h1><p>${text}</p></div></div>`; }

async function hydrateFromSupabase(){
  if (!db) return;
  try {
    const [{ data: companies, error: companyError }, { data: jobs, error: jobError }] = await Promise.all([
      db.from('companies').select('id,name,slug,city,industry,description,approved').order('created_at', { ascending: false }),
      db.from('jobs').select('id,title,slug,description,contract_type,salary_text,deadline,status,featured,companies(name),categories(name),cities(name)').in('status', ['active','pending_review']).order('created_at', { ascending: false })
    ]);
    if (!companyError && companies?.length) {
      state.companies = companies.map(c => ({ id:c.id, name:c.name, logo:initials(c.name), city:c.city || 'Crna Gora', industry:c.industry || 'Poslodavac', jobs:0, about:c.description || 'Profil poslodavca.' }));
    }
    if (!jobError && jobs?.length) {
      state.jobs = jobs.map(j => ({ id:j.id, title:j.title, company:j.companies?.name || 'Poslodavac', logo:initials(j.companies?.name), city:j.cities?.name || 'Crna Gora', category:j.categories?.name || 'Ostalo', type:j.contract_type || 'Po dogovoru', salary:j.salary_text || 'Po dogovoru', deadline:j.deadline || 'Otvoren konkurs', featured:Boolean(j.featured), description:j.description || 'Opis oglasa nije unesen.' }));
    }
    if (!companyError || !jobError) state.mode = 'supabase';
  } catch (error) {
    console.warn('Supabase nije spreman, koristim demo podatke.', error);
  }
}

function searchPanel(){ return `<form class="search-panel" data-search><input class="field" name="q" placeholder="Pozicija, firma ili vjestina"><select class="select" name="city"><option value="">Svi gradovi</option>${cities().map(c=>`<option>${h(c)}</option>`).join('')}</select><select class="select" name="category"><option value="">Sve kategorije</option>${categories().map(c=>`<option>${h(c)}</option>`).join('')}</select><button class="primary-button">Trazi</button></form>`; }
function jobCard(job){ return `<article class="job-card"><div class="logo">${h(job.logo)}</div><div><div class="tags">${job.featured?'<span class="status amber">Istaknuto</span>':''}<span class="tag">${h(job.category)}</span><span class="tag">${h(job.type)}</span></div><h3><a href="#/oglasi/${slug(job.title)}-${job.id}">${h(job.title)}</a></h3><div class="meta"><span>${h(job.company)}</span><span>${h(job.city)}</span><span>${h(job.salary)}</span><span>Rok ${h(job.deadline)}</span></div><p class="muted" style="margin-top:10px">${h(job.description)}</p></div><div class="job-actions"><a class="small-button" href="#/oglasi/${slug(job.title)}-${job.id}">Detalji</a><button class="primary-button small-button" data-apply="${job.id}">Prijavi se</button></div></article>`; }
function companyCard(company){ return `<article class="company-card"><div class="logo">${h(company.logo)}</div><div><h3><a href="#/firme/${slug(company.name)}-${company.id}">${h(company.name)}</a></h3><p>${h(company.about)}</p><div class="meta"><span>${h(company.city)}</span><span>${h(company.industry)}</span><span>${company.jobs} oglasa</span></div></div></article>`; }

function home(){ app().innerHTML = `<section class="hero"><div class="panel"><span class="eyebrow">Poslovi u Crnoj Gori</span><h1>Nadji posao ili kandidata bez lutanja.</h1><p class="lead">imaposla.me povezuje kandidate, firme i administraciju u jasan sistem: oglasi, prijave, CV, ATS i moderacija na jednom mjestu.</p><p class="muted" style="margin-top:10px">Izvor podataka: ${state.mode === 'supabase' ? 'Supabase baza' : 'demo podaci dok ne pokrenemo bazu'}.</p><div class="hero-actions"><a class="primary-button" href="#/oglasi">Pretrazi oglase</a><a class="ghost-button" href="#/za-firme">Rjesenje za firme</a></div>${searchPanel()}</div><aside class="hero-side"><div class="metric-grid">${metric('aktivna oglasa',state.jobs.length)}${metric('poslodavca',state.companies.length)}${metric('prijave u ATS-u',state.applications.length)}${metric('korisnicke uloge',3)}</div><div class="guide-card"><h3>Jasno po ulogama</h3><p>Kandidat vidi CV i prijave. Firma vidi oglase i ATS. Admin vidi moderaciju, uplate i korisnike.</p></div></aside></section><section>${heading('Kako radi','Prva verzija je zamisljena da bude razumljiva bez obuke.')}<div class="grid three">${panel('Kandidat','Trazi posao, cuva CV, prijavljuje se i prati status prijave.')}${panel('Firma','Objavljuje oglase, pregleda prijave, vodi ATS i upravlja pretplatom.')}${panel('Admin','Odobrava firme i oglase, potvrdjuje uplate i prati statistiku.')}</div></section><section>${heading('Izdvojeni oglasi','Primjeri kartica koje dolaze iz demo podataka ili Supabase baze.')}<div class="job-list">${state.jobs.filter(j=>j.featured).map(jobCard).join('') || state.jobs.slice(0,2).map(jobCard).join('')}</div></section>`; }
function jobs(pref={}){ const params=new URLSearchParams(location.hash.split('?')[1]||''); const q=(params.get('q')||'').toLowerCase(); const city=pref.city||params.get('city')||''; const category=pref.category||params.get('category')||''; const list=state.jobs.filter(j=>(!q||`${j.title} ${j.company} ${j.category}`.toLowerCase().includes(q))&&(!city||j.city===city)&&(!category||j.category===category)); app().innerHTML = `${heading('Oglasi za posao','Filteri su spremni za bazu i SEO stranice po gradovima/kategorijama.')}${searchPanel()}<div class="job-list">${list.map(jobCard).join('') || '<div class="empty">Nema oglasa za izabrane filtere.</div>'}</div>`; }
function jobDetail(raw){ const id=Number((raw.match(/-(\d+)$/)||[])[1]); const job=state.jobs.find(j=>j.id===id)||state.jobs[0]; app().innerHTML = `<a class="ghost-button small-button" href="#/oglasi">Nazad na oglase</a><section class="grid two" style="margin-top:16px"><div class="panel"><span class="eyebrow">${h(job.category)}</span><h1>${h(job.title)}</h1><p class="lead">${h(job.description)}</p><div class="meta" style="margin-top:18px"><span>${h(job.company)}</span><span>${h(job.city)}</span><span>${h(job.salary)}</span><span>${h(job.type)}</span></div><div class="section-head"><div><h2>Sta kandidat vidi</h2><p>Opis posla, uslovi, rok i jasna prijava sa CV fajlom.</p></div></div><div class="grid two">${panel('Prijava','Ime, kontakt, CV fajl i kratka poruka firmi.')}${panel('Privatnost','Kontakt se koristi samo za ovu prijavu i bice definisan pravilima platforme.')}</div></div><aside class="form-card"><h2>Prijavi se</h2><label><span class="label">Ime i prezime</span><input class="field" placeholder="npr. Ana Petrovic"></label><label><span class="label">Email</span><input class="field" placeholder="ana@email.com"></label><label><span class="label">CV fajl</span><input class="field" type="file"></label><label><span class="label">Poruka</span><textarea class="textarea" placeholder="Kratko predstavljanje"></textarea></label><button class="primary-button" data-apply="${job.id}">Posalji prijavu</button></aside></section>`; }
function citiesPage(){ app().innerHTML = `${heading('Gradovi','SEO hub stranice za pretragu poslova po gradu.')}<div class="grid three">${cities().map(c=>panel(h(c),`<a href="#/gradovi/${encodeURIComponent(c)}">Pogledaj oglase u gradu ${h(c)}</a>`)).join('')}</div>`; }
function categoriesPage(){ app().innerHTML = `${heading('Kategorije','Kategorije pomazu kandidatima i Google indeksiranju.')}<div class="grid three">${categories().map(c=>panel(h(c),`<a href="#/kategorije/${encodeURIComponent(c)}">Pogledaj oglase: ${h(c)}</a>`)).join('')}</div>`; }
function companies(){ app().innerHTML = `${heading('Firme','Javni profili poslodavaca sa aktivnim oglasima.')}<div class="grid two">${state.companies.map(companyCard).join('')}</div>`; }
function companyDetail(raw){ const id=Number((raw.match(/-(\d+)$/)||[])[1]); const company=state.companies.find(c=>c.id===id)||state.companies[0]; const list=state.jobs.filter(j=>j.company===company.name); app().innerHTML = `<a class="ghost-button small-button" href="#/firme">Nazad na firme</a><div class="panel" style="margin-top:16px"><span class="eyebrow">Profil firme</span><h1>${h(company.name)}</h1><p class="lead">${h(company.about)}</p></div>${heading('Aktivni oglasi','Svi javni oglasi ovog poslodavca.')}<div class="job-list">${list.map(jobCard).join('') || '<div class="empty">Firma trenutno nema aktivnih oglasa.</div>'}</div>`; }
function forCompanies(){ app().innerHTML = `<section class="panel"><span class="eyebrow">Za poslodavce</span><h1>Objavite oglas, pratite prijave i vodite selekciju.</h1><p class="lead">Firma dobija dashboard, oglase, ATS, bazu kandidata i pretplatu. Admin odobrava osjetljive korake.</p><div class="hero-actions"><a class="primary-button" href="#/firma/novi-oglas">Objavi prvi oglas</a><a class="ghost-button" href="#/firma/dashboard">Pogledaj demo firme</a></div></section>${heading('Sta firma dobija','')}<div class="grid three">${panel('Oglasi','Objava, statusi, rokovi, gradovi i kategorije.')}${panel('ATS','Kanban faze, komentari, oznake i istorija prijava.')}${panel('Pretplata','Planovi, uplate i krediti po pravilima plana.')}</div>`; }

function shell(role,page){ app().innerHTML = `<div class="shell"><aside class="sidebar"><h3>${roleTitle[role]}</h3><p>${state.mode === 'supabase' ? 'Supabase je povezan.' : 'Demo prostor za ulogu.'}</p>${menus[role].map(([label,url])=>`<a class="${path()===url?'active':''}" href="#${url}">${label}</a>`).join('')}</aside><section>${rolePage(role,page)}</section></div>`; }
function rolePage(role,page){ return role==='candidate'?candidate(page):role==='company'?company(page):admin(page); }
function candidate(page){ if(page==='cv')return heading('CV profil','Podaci koje kandidat kontrolise.')+profileForm('Milica Radovic'); if(page==='applications')return heading('Moje prijave','Status prijava i referentni broj.')+table([['Konobar/konobarica','Hotel Sunce','Poslato','IP-A-100'],['Recepcionar','Adria Suites','Razgovor','IP-A-101']]); if(page==='notifications')return heading('Obavjestenja','Poruke o statusu prijava.')+`<div class="grid">${panel('Prijava pregledana','Hotel Sunce je otvorio tvoju prijavu.')}${panel('Novi oglas','Recepcionar u Kotoru odgovara tvom profilu.')}</div>`; if(page==='settings')return heading('Podesavanja','Email, lozinka i privatnost profila.')+settingsForm('Kandidat'); return heading('Kandidat dashboard','Pregled profila, prijava i preporucenih poslova.')+`<div class="dash-grid">${metric('Kompletan CV','72%')}${metric('Aktivne prijave','3')}${metric('Obavjestenja','2')}${metric('Sacuvani oglasi','5')}</div><div class="job-list">${state.jobs.slice(0,2).map(jobCard).join('')}</div>`; }
function company(page){ if(page==='jobs')return heading('Moji oglasi','Statusi, prijave i brzo upravljanje.')+`<div class="job-list">${state.jobs.map(jobCard).join('')}</div>`; if(page==='new-job')return heading('Novi oglas','Forma je spremna za snimanje u tabelu jobs.')+jobForm(); if(page==='ats')return heading('ATS prijave','Kanban po fazama selekcije, komentarima i oznakama.')+kanban(); if(page==='candidates')return heading('Baza kandidata','Pretraga javnih profila i kontrolisano otkljucavanje kontakta.')+`<div class="grid two">${state.applications.map(a=>panel(a.candidate,`${a.title}, ${a.city}. Kontakt je zakljucan dok pravila privatnosti ne dozvole prikaz.`)).join('')}</div>`; if(page==='billing')return heading('Pretplata','Manualna uplata u prvoj fazi, kartice kasnije.')+`<div class="grid three">${['Starter 25 EUR','Growth 80 EUR','Pro 200 EUR'].map(p=>panel(p,'Oglasi, ATS i krediti po pravilima plana.')).join('')}</div>`; if(page==='banners')return heading('Baneri','Promo pozicije i statistika za firme.')+bannerForm(); if(page==='settings')return heading('Podesavanja firme','Logo, profil firme, kontakt i clanovi tima.')+settingsForm('Firma'); return heading('Firma dashboard','Brze akcije, oglasi i prijave koje traze paznju.')+`<div class="dash-grid">${metric('Aktivni oglasi','4')}${metric('Nove prijave','24')}${metric('Razgovori','6')}${metric('Krediti','24')}</div><div class="grid two">${panel('Sljedeci korak','Pregledaj nove prijave za Konobar/konobarica.')}${panel('Moderacija','Jedan oglas ceka odobrenje admina.')}</div>`; }
function admin(page){ if(page==='payments')return heading('Uplate i kodovi','Admin potvrdjuje bankovne uplate i generise aktivaciju.')+table(state.orders.map(o=>[o.id,o.company,o.plan,o.status])); if(page==='jobs')return heading('Moderacija oglasa','Odobravanje, pauziranje i isticanje oglasa.')+`<div class="job-list">${state.jobs.map(jobCard).join('')}</div>`; if(page==='users')return heading('Korisnici','Kandidati, firme i status verifikacije.')+table([['Milica Radovic','Kandidat','Aktivan','Pregled'],['Hotel Sunce','Firma','Odobrena','Pregled'],['Adria Suites','Firma','Ceka provjeru','Odobri']]); if(page==='banners')return heading('Baneri','Admin odobrava promo pozicije.')+table([['Ljetnja sezona','Hotel Sunce','Ceka odobrenje','Home'],['Prodaja','Market Plus','Aktivan','Oglasi']]); if(page==='stats')return heading('Statistike','Prihod, trendovi i aktivnost platforme.')+`<div class="dash-grid">${metric('Prihod','105 EUR')}${metric('Oglasi','4')}${metric('Prijave','80')}${metric('Firme','3')}</div>`; return heading('Admin dashboard','Operativni pregled zadataka.')+`<div class="dash-grid">${metric('Uplate za potvrdu','1')}${metric('Oglasi za pregled','1')}${metric('Nove firme','1')}${metric('Prijave danas','12')}</div><div class="grid two">${panel('Prioritet','Provjeri firmu Adria Suites i oglas Recepcionar.')}${panel('Sigurnost','Admin akcije moraju ici preko Supabase RLS politika.')}</div>`; }
function profileForm(name){ return `<form class="form-card"><div class="form-grid"><label><span class="label">Ime/Naziv</span><input class="field" value="${name}"></label><label><span class="label">Grad</span><input class="field" value="Budva"></label></div><label><span class="label">Opis</span><textarea class="textarea">Kratak profil koji se prikazuje u aplikaciji.</textarea></label><label><span class="label">Fajl/slika</span><input class="field" type="file"></label><button class="primary-button" type="button" data-demo-save>Sacuvaj izmjene</button></form>`; }
function settingsForm(title){ return `<form class="form-card"><h3>${title}</h3><label><span class="label">Email</span><input class="field" value="demo@imaposla.me"></label><label><span class="label">Lozinka</span><input class="field" type="password" value="password"></label><button class="primary-button" type="button" data-demo-save>Sacuvaj podesavanja</button></form>`; }
function jobForm(){ return `<form class="form-card"><div class="form-grid"><label><span class="label">Naziv pozicije</span><input class="field" id="newJobTitle" placeholder="npr. Kuvar"></label><label><span class="label">Grad</span><select class="select">${cities().map(c=>`<option>${h(c)}</option>`).join('')}</select></label></div><label><span class="label">Opis oglasa</span><textarea class="textarea" placeholder="Opis posla, uslovi, benefiti..."></textarea></label><button class="primary-button" type="button" data-create-job>Objavi demo oglas</button></form>`; }
function bannerForm(){ return `<form class="form-card"><label><span class="label">Naziv kampanje</span><input class="field" placeholder="npr. Ljetnja sezona"></label><label><span class="label">Slika banera</span><input class="field" type="file"></label><button class="primary-button" type="button" data-demo-save>Posalji na odobrenje</button></form>`; }
function table(rows){ return `<div class="table-card">${rows.map(row=>`<div class="table-row">${row.map((cell,i)=>`<div>${i===0?`<strong>${h(cell)}</strong>`:h(cell)}</div>`).join('')}</div>`).join('')}</div>`; }
function kanban(){ const stages=['Prijava','Pregled','Razgovor','Uzi izbor','Ponuda']; return `<div class="kanban-wrap"><div class="kanban">${stages.map(stage=>{ const apps=state.applications.filter(a=>a.stage===stage); return `<div class="kanban-column"><div class="kanban-head"><span>${stage}</span><span>${apps.length}</span></div>${apps.map(a=>`<div class="candidate-card"><strong>${h(a.candidate)}</strong><p>${h(a.title)}, ${h(a.city)}</p><div class="tags">${a.labels.map(l=>`<span class="tag">${h(l)}</span>`).join('')}</div><p>${h(a.note)}</p><div class="candidate-actions"><button class="small-button" data-demo-save>Nazad</button><button class="primary-button small-button" data-demo-save>Dalje</button></div></div>`).join('') || '<div class="empty">Nema prijava.</div>'}</div>`; }).join('')}</div></div>`; }
function loginPage(){ app().innerHTML = `<section class="grid two"><form class="form-card" data-auth-form="signin"><span class="eyebrow">Prijava</span><h1>Udji na nalog</h1><p class="muted">Email i lozinka rade preko Supabase Auth-a cim pokrenemo semu baze.</p><label><span class="label">Email</span><input class="field" name="email" type="email" required placeholder="ime@email.com"></label><label><span class="label">Lozinka</span><input class="field" name="password" type="password" required placeholder="Najmanje 6 karaktera"></label><button class="primary-button">Prijavi se</button></form><form class="form-card" data-auth-form="signup"><span class="eyebrow">Registracija</span><h1>Novi nalog</h1><p class="muted">Izaberi da li pravis nalog kao kandidat ili firma.</p><label><span class="label">Tip naloga</span><select class="select" name="role"><option value="candidate">Kandidat</option><option value="company">Firma</option></select></label><label><span class="label">Email</span><input class="field" name="email" type="email" required placeholder="ime@email.com"></label><label><span class="label">Lozinka</span><input class="field" name="password" type="password" required placeholder="Najmanje 6 karaktera"></label><button class="primary-button">Registruj se</button><div class="hero-actions"><button class="ghost-button" type="button" data-role-login="candidate">Demo kandidat</button><button class="ghost-button" type="button" data-role-login="company">Demo firma</button><button class="ghost-button" type="button" data-role-login="admin">Demo admin</button></div></form></section>`; }
function staticPage(title,text){ app().innerHTML = `<section class="panel"><h1>${title}</h1><p class="lead">${text}</p></section>`; }
function sitemap(){ staticPage('Sitemap','Javno: pocetna, oglasi, detalj oglasa, gradovi, kategorije, firme, login. Kandidat, firma i admin imaju odvojene dashboarde.'); }
function notFound(){ staticPage('Stranica nije pronadjena','Provjeri adresu ili se vrati na pocetnu.'); }

const routes = {'/':home,'/oglasi':jobs,'/gradovi':citiesPage,'/kategorije':categoriesPage,'/firme':companies,'/za-firme':forCompanies,'/login':loginPage,'/profil/dashboard':()=>shell('candidate','dashboard'),'/profil/cv':()=>shell('candidate','cv'),'/profil/prijave':()=>shell('candidate','applications'),'/profil/obavijesti':()=>shell('candidate','notifications'),'/profil/podesavanja':()=>shell('candidate','settings'),'/firma/dashboard':()=>shell('company','dashboard'),'/firma/oglasi':()=>shell('company','jobs'),'/firma/novi-oglas':()=>shell('company','new-job'),'/firma/ats':()=>shell('company','ats'),'/firma/kandidati':()=>shell('company','candidates'),'/firma/pretplata':()=>shell('company','billing'),'/firma/baneri':()=>shell('company','banners'),'/firma/podesavanja':()=>shell('company','settings'),'/admin/dashboard':()=>shell('admin','dashboard'),'/admin/uplate':()=>shell('admin','payments'),'/admin/oglasi':()=>shell('admin','jobs'),'/admin/korisnici':()=>shell('admin','users'),'/admin/baneri':()=>shell('admin','banners'),'/admin/statistike':()=>shell('admin','stats'),'/politika-privatnosti':()=>staticPage('Politika privatnosti','Ovdje ce stajati finalna pravila obrade CV fajlova, kontakt podataka i prava kandidata.'),'/uslovi-koristenja':()=>staticPage('Uslovi koriscenja','Ovdje ce stajati pravila koriscenja za kandidate, firme i administratore.'),'/sitemap':sitemap};
function render(){ const p=path(); const job=p.match(/^\/oglasi\/(.+)/); const company=p.match(/^\/firme\/(.+)/); const city=p.match(/^\/gradovi\/(.+)/); const cat=p.match(/^\/kategorije\/(.+)/); if(job)return jobDetail(job[1]); if(company)return companyDetail(company[1]); if(city)return jobs({city:decodeURIComponent(city[1])}); if(cat)return jobs({category:decodeURIComponent(cat[1])}); (routes[p]||notFound)(); document.querySelectorAll('.desktop-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+p)); app().focus({preventScroll:true}); }

document.addEventListener('submit', async event => {
  if (event.target.matches('[data-search]')) { event.preventDefault(); const data=new FormData(event.target); const params=new URLSearchParams(); ['q','city','category'].forEach(k=>{ if(data.get(k)) params.set(k,data.get(k)); }); location.hash='/oglasi?'+params.toString(); return; }
  const form = event.target.closest('[data-auth-form]');
  if (!form) return;
  event.preventDefault();
  if (!db) return toast('Supabase klijent nije ucitan.');
  const data = new FormData(form);
  const email = String(data.get('email') || '');
  const password = String(data.get('password') || '');
  const role = String(data.get('role') || 'candidate');
  try {
    if (form.dataset.authForm === 'signup') {
      const { error } = await db.auth.signUp({ email, password, options: { data: { role } } });
      if (error) throw error;
      toast('Registracija poslata. Provjeri email ako je potvrda ukljucena.');
    } else {
      const { error } = await db.auth.signInWithPassword({ email, password });
      if (error) throw error;
      state.role = role;
      toast('Prijava uspjesna.');
      go('/profil/dashboard');
    }
  } catch (error) { toast(error.message || 'Auth greska.'); }
});

document.addEventListener('click', event => {
  const target = event.target.closest('button,a');
  if (!target) return;
  if (target.matches('[data-action="toggle-menu"]')) document.querySelector('[data-mobile-menu]').classList.toggle('open');
  if (target.matches('[data-action="open-login"]')) document.querySelector('[data-modal]').classList.add('open');
  if (target.matches('[data-action="close-login"]')) document.querySelector('[data-modal]').classList.remove('open');
  if (target.matches('[data-role-login]')) { const role=target.dataset.roleLogin; state.role=role; localStorage.setItem('imaposlaRole',role); document.querySelector('[data-modal]').classList.remove('open'); toast('Demo prijava: '+roleTitle[role]); go(role==='candidate'?'/profil/dashboard':role==='company'?'/firma/dashboard':'/admin/dashboard'); }
  if (target.matches('[data-apply]')) toast('Demo prijava je zabiljezena. Nakon Supabase veze bice snimljena u bazu.');
  if (target.matches('[data-demo-save]')) toast('Demo izmjena sacuvana za prikaz.');
  if (target.matches('[data-create-job]')) { const title=document.querySelector('#newJobTitle')?.value?.trim()||'Novi oglas'; state.jobs.unshift({id:Date.now(),title,company:'Hotel Sunce',logo:'HS',city:'Budva',category:'Ugostiteljstvo',type:'Stalni rad',salary:'Po dogovoru',deadline:'30.06.2026',featured:false,description:'Oglas ceka admin odobrenje.'}); toast('Demo oglas je dodat i ceka moderaciju.'); go('/firma/oglasi'); }
});

window.addEventListener('hashchange', render);
app().innerHTML = '<section class="panel"><span class="eyebrow">Ucitavanje</span><h1>Spremamo imaposla.me</h1><p class="lead">Provjeravam da li je Supabase baza dostupna.</p></section>';
hydrateFromSupabase().finally(render);
