'use client'

import { useEffect, useMemo, useState } from 'react'
import { accommodationType, bookingOpportunity, hardGate, liveEligibility, premiumScore, scoreStatus } from '../lib/engine'

const emptyScores={artDirection:0,photography:0,content:0,typography:0,layout:0,mobile:0,conversion:0,accessibility:0,performance:0,technical:0}
const qaKeys=['content','image','accessibility','responsive','artDirection','similarity','standalone']

export default function Page(){
  const [projects,setProjects]=useState([]),[selected,setSelected]=useState(null),[tab,setTab]=useState('overview'),[busy,setBusy]=useState(true),[notice,setNotice]=useState('Učitavam stvarne Factory projekte...'),[city,setCity]=useState(''),[category,setCategory]=useState('')
  async function load(){setBusy(true);try{const r=await fetch('/api/projects',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Load failed');setProjects(d.projects||[]);setSelected(s=>s&&d.projects.some(x=>x.id===s)?s:d.projects?.[0]?.id);setNotice(`${d.projects?.length||0} stvarnih projekata učitano iz Factory baze.`)}catch(e){setNotice(`Greška: ${e.message}`)}finally{setBusy(false)}}
  useEffect(()=>{load()},[])
  const p=projects.find(x=>x.id===selected)||projects[0]
  const liveCount=useMemo(()=>projects.filter(x=>x.registryStatus==='LIVE_DEMO'&&x.liveUrl).length,[projects])
  const todayCount=useMemo(()=>projects.filter(x=>String(x.updatedAt||'').startsWith('2026-09-09')).length,[projects])
  async function savePatch(id,data){setProjects(list=>list.map(x=>x.id===id?{...x,...data}:x));try{const r=await fetch('/api/projects',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,patch:data})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Save failed');if(d.project)setProjects(list=>list.map(x=>x.id===id?d.project:x))}catch(e){setNotice(`Nije sačuvano: ${e.message}`);load()}}
  function patch(data){if(p)savePatch(p.id,data)}
  function patchNested(key,data){patch({[key]:{...(p[key]||{}),...data}})}
  async function generate(){setBusy(true);setNotice('Discovery radi...');try{const r=await fetch('/api/daily-batch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({cities:city?[city]:undefined,categories:category?[category]:undefined})}),d=await r.json();setNotice(d.message||`Discovery završen. Kandidata: ${d.projects?.length||0}.`);await load()}catch(e){setNotice(`Greška: ${e.message}`)}finally{setBusy(false)}}
  if(!p&&!busy)return <div className="factory-shell"><main className="factory-main"><header className="factory-top"><div><span className="eyebrow">FACTORY DATABASE</span><h1>Nema projekata</h1><p>{notice}</p></div><button className="btn primary" onClick={load}>REFRESH</button></header></main></div>
  if(!p)return <div className="factory-shell"><main className="factory-main"><header className="factory-top"><h1>Učitavam Factory...</h1></header></main></div>
  const gate=hardGate(p),eligibility=liveEligibility(p),score=Number(p.scores?.premium_score??p.scores?.premiumScore??premiumScore(p.scores)),book=p.bookingOpportunity||bookingOpportunity(p)
  return <div className="factory-shell"><aside className="factory-side"><div className="logo">MF</div><div className="brand"><strong>MINI-SAJT FACTORY</strong><span>LIVE CONTROL</span></div><div className="side-group"><span>DANAS</span><b>{todayCount}</b></div><div className="side-group"><span>UKUPNO U BAZI</span><b>{projects.length}</b></div><div className="side-group"><span>LIVE DEMO</span><b>{liveCount}</b></div><div className="side-group"><span>OUTPUT</span><small>preporuke/{'{slug}'}/index.html</small></div><div className="side-foot">Supabase: factory_projects</div></aside><main className="factory-main">
  <header className="factory-top"><div><span className="eyebrow">DAILY PRODUCTION</span><h1>Kontrolna tabla</h1><p>Stvarni Factory projekti - bez demo seed podataka.</p></div><div className="top-actions"><button className="btn ghost" onClick={load} disabled={busy}>REFRESH</button><button className="btn primary" onClick={generate} disabled={busy}>{busy?'RADI...':'GENERATE 5 NOW'}</button></div></header>
  {notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<b>×</b></div>}<section className="filters"><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Grad - Kotor"/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Kategorija - restoran"/><span>Prikaz je vezan za Factory bazu.</span></section>
  <section className="project-row">{projects.map((x,i)=>{const s=Number(x.scores?.premium_score??x.scores?.premiumScore??premiumScore(x.scores));return <button className={`project-card ${x.id===p.id?'active':''}`} key={x.id} onClick={()=>{setSelected(x.id);setTab('overview')}}><small>{String(i+1).padStart(2,'0')} · {x.type}</small><h3>{x.name}</h3><p>{x.city||'Grad nije potvrđen'}</p><div><span>{x.stage}</span><b>{s}/100</b></div></button>})}</section>
  <section className="workspace"><div className="project-head"><div><span className="eyebrow">ACTIVE PROJECT</span><h2>{p.name}</h2><p>{p.type} · {p.city}</p></div><div className={`score ${score>=85?'good':'bad'}`}><b>{score}</b><span>/100</span><small>{scoreStatus(score)}</small></div></div><nav className="tabs">{['overview','research','design','qa','sales'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t.toUpperCase()}</button>)}</nav>
  {tab==='overview'&&<div className="grid2"><Panel title="Hard gates"><Gate ok={p.registryStatus!=='LIVE_DEMO'&&!String(p.registryStatus).startsWith('SKIPPED')} label="Registry / dedupe" value={p.registryStatus}/><Gate ok={p.operatingStatus==='RADI'} label="Status rada" value={p.operatingStatus}/><Gate ok={p.hasOwnSite===false} label="Sopstveni sajt" value={p.hasOwnSite===false?'NEMA':'IMA / NEPOZNATO'}/><div className={`decision ${gate.pass?'good':'bad'}`}><b>{gate.pass?'GRADI':'NE GRADI'}</b><span>{gate.pass?'Hard gateovi prolaze':gate.reasons.join(' · ')}</span></div></Panel><Panel title="Live status"><Metric label="Premium Score" value={`${score}/100`}/><Metric label="Stage" value={p.stage}/><Metric label="Registry" value={p.registryStatus}/><Metric label="Live URL" value={p.liveUrl||'NIJE LIVE'}/><Metric label="Booking" value={book}/></Panel><Panel title="QA stanje"><Metric label="Owner voice" value={p.qa?.owner_voice||p.qa?.ownerVoice||'NIJE EVIDENTIRANO'}/><Metric label="Page depth" value={p.qa?.page_depth||'NIJE EVIDENTIRANO'}/><Metric label="Structural difference" value={p.qa?.structural_difference||'NIJE EVIDENTIRANO'}/><Metric label="Browser" value={p.qa?.browser_visual_qa||p.qa?.browser_executed||'NIJE IZVRŠEN'}/></Panel><Panel title="Output"><Metric label="Repo folder" value={`preporuke/${p.slug}/index.html`}/><Metric label="Updated" value={p.updatedAt}/></Panel></div>}
  {tab==='research'&&<div className="grid2"><Panel title="Identitet"><Field label="Naziv" value={p.name} onChange={v=>patch({name:v})}/><Field label="Grad" value={p.city} onChange={v=>patch({city:v})}/><Field label="Tip" value={p.type} onChange={v=>patch({type:v})}/><Select label="Status rada" value={p.operatingStatus} options={['RADI','PRIVREMENO ZATVORENO','TRAJNO ZATVORENO','NEPOZNATO']} onChange={v=>patch({operatingStatus:v})}/><Select label="Ima svoj sajt" value={String(p.hasOwnSite)} options={['false','true']} onChange={v=>patch({hasOwnSite:v==='true'})}/></Panel><Panel title="Kvalifikacija"><Select label="Lead ocjena" value={p.grade} options={['A','B','C','D','PRESKOČITI']} onChange={v=>patch({grade:v})}/><Metric label="Telefon" value={p.phone||'NIJE EVIDENTIRAN'}/><Metric label="Mapa" value={p.mapConfirmed?'POTVRĐENA':'NIJE EVIDENTIRANA'}/><Metric label="Prodajni ugao" value={p.salesAngle||'NIJE EVIDENTIRAN'}/></Panel></div>}
  {tab==='design'&&<div className="grid2"><Panel title="Design DNA">{Object.entries(p.designDna||{}).map(([k,v])=><Metric key={k} label={k} value={Array.isArray(v)?v.join(' · '):typeof v==='object'?JSON.stringify(v):String(v)}/>)}</Panel><Panel title="Premium pravilo"><p className="quote">Standardizuj kvalitet, funkcionalnost i kontrolu. Ne standardizuj izgled.</p><Metric label="Signature" value={p.designDna?.signature_component||p.designDna?.signatureComponent||'NIJE EVIDENTIRAN'}/></Panel></div>}
  {tab==='qa'&&<div className="grid2"><Panel title="Stvarni QA zapisi">{Object.entries(p.qa||{}).map(([k,v])=><Metric key={k} label={k} value={String(v)}/>)}</Panel><Panel title="Score zapisi">{Object.entries(p.scores||{}).map(([k,v])=><Metric key={k} label={k} value={String(v)}/>)}</Panel></div>}
  {tab==='sales'&&<div className="grid2"><Panel title="Sales gate"><Metric label="Kontakt status" value={p.contactStatus||'READY'}/><p>Kontrolna tabla ne šalje prospectu ništa automatski. Slanje ostaje approval-gated.</p></Panel>{accommodationType(p.type)&&<Panel title="Accommodation booking"><Metric label="Opportunity" value={book}/><Metric label="Approval" value={p.bookingApproval?'ODOBRENO':'NIJE ODOBRENO'}/></Panel>}</div>}
  </section></main></div>}
function Panel({title,children}){return <article className="panel"><h3>{title}</h3>{children}</article>}function Gate({ok,label,value}){return <div className="gate"><i className={ok?'good':'bad'}>{ok?'✓':'×'}</i><span><b>{label}</b><small>{value}</small></span></div>}function Metric({label,value}){return <div className="metric"><span>{label}</span><b>{value||'-'}</b></div>}function Field({label,value,onChange}){return <label className="field"><span>{label}</span><input value={value??''} onChange={e=>onChange(e.target.value)}/></label>}function Select({label,value,onChange,options}){return <label className="field"><span>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
